"""empty message

Revision ID: 031438d291da
Revises: 01e5d9fe1652
Create Date: 2020-01-18 13:50:07.786234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031438d291da'
down_revision = '01e5d9fe1652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('neutral', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('query', sa.Column('result_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'query', 'result', ['result_id'], ['id'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'query', type_='foreignkey')
    op.drop_column('query', 'result_id')
    op.drop_table('result')
    # ### end Alembic commands ###
