"""empty message

Revision ID: 4f56d8f81697
Revises: 5e5ecdf8e962
Create Date: 2020-01-27 03:25:59.824004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f56d8f81697'
down_revision = '5e5ecdf8e962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('query_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'query', ['query_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'query_id')
    # ### end Alembic commands ###
