"""empty message

Revision ID: 52c22cf76462
Revises: 7fc60bf4dfa5
Create Date: 2020-01-27 23:52:46.388536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c22cf76462'
down_revision = '7fc60bf4dfa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query', 'percent')
    # ### end Alembic commands ###
