"""empty message

Revision ID: 7fc60bf4dfa5
Revises: 4f56d8f81697
Create Date: 2020-01-27 04:08:19.034901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fc60bf4dfa5'
down_revision = '4f56d8f81697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'query', 'user', ['user'], ['id'])
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'query_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('query_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'query', ['query_id'], ['id'])
    op.drop_constraint(None, 'query', type_='foreignkey')
    op.drop_column('query', 'user')
    # ### end Alembic commands ###
